export const SERVERS_LIST_REQUEST = 'SERVERS_LIST_REQUEST';
export const SERVERS_LIST_SUCCESS = 'SERVERS_LIST_SUCCESS';
export const SERVERS_LIST_FAIL = 'SERVERS_LIST_FAIL';
export const SERVERS_LIST_RESET = 'SERVERS_LIST_RESET';
export const SERVERS_LIST_SORT = 'SERVERS_LIST_SORT';
